Repository uBeom/sidedish, pull requests merged in 2022-04, with the labels that each got.

#8 [포키] 카드 호버시 딤드 레이어 노출, 슬라이딩 카테고리 렌더링 구현
  app/src/components/App.js
  app/src/components/Card.js
  app/src/components/CardList.js
  app/src/components/Category.js
  app/src/components/Header.js
  app/src/components/MainTab.js
Labels: feature

#7 [베니] Modal Content 부분 마크업, 스타일 구현
  app/public/images/Minus.svg
  app/public/images/Plus.svg
  app/src/components/App.js
  app/src/components/Card.js
  app/src/components/Modal.js
  app/src/styles/theme.js
  app/src/styles/utils.js
Labels: feature

#9 Modal 컴포넌트 리팩토링, ModalCarosuel 컴포넌트 마크업, 스타일
  app/public/images/ModalCarouselLeft.svg
  app/public/images/ModalCarouselRight.svg
  app/src/components/App.js
  app/src/components/Card.js
  app/src/components/Category.js
  app/src/components/Modal.js
  app/src/components/Modal/Alert.js
  app/src/components/Modal/Carousel.js
  app/src/components/Modal/Modal.js
  app/src/components/Modal/Product.js
  app/src/contexts/ModalContext.js
  app/src/index.js
  app/src/styles/Modal/Alert.js
  app/src/styles/Modal/Carousel.js
  app/src/styles/Modal/Modal.js
  app/src/styles/Modal/Product.js
  app/src/styles/utils.js
Labels: feature

#10 카테고리 슬라이딩 기능 구현
  README.md
  app/src/components/App.js
  app/src/components/Card.js
  app/src/components/CardList.js
  app/src/components/Category.js
  app/src/components/MainTab.js
  app/src/components/Slider.js
  app/src/styles/theme.js
  app/src/styles/utils.js
Labels: feature

#13 모달 컴포넌트 캐러셀 구현
  app/public/images/ModalCarouselLeft.svg
  app/src/components/Modal/Carousel.js
  app/src/components/Modal/Product.js
  app/src/styles/Modal/Carousel.js
Labels: feature

#14 #11 카테고리 펼침 기능 추가
  app/public/images/Arrow_black.svg
  app/public/images/Arrow_grey.svg
  app/src/components/Category.js
  app/src/components/MainCategories.js
  app/src/components/Slider.js
Labels: feature

#15 Modal 캐러셀 버튼 이미지 변경 기능 구현
  app/public/images/ModalCarouselLeftDisable.svg
  app/public/images/ModalCarouselRightDisable.svg
  app/src/components/Modal/Carousel.js
Labels: feature

#18 Feat: 모달 컴포넌트 배경, 스크롤바 기능 구현, Hotfix: 이미지 마우스 오버시 이미지 변경 안됨
  app/src/components/App.jsx
  app/src/components/Card.jsx
  app/src/components/MainTab.jsx
  app/src/components/Modal/Alert.jsx
  app/src/components/Modal/Modal.jsx
  app/src/components/Modal/ProductDetailModal.jsx
  app/src/styled-components/utils.js
Labels: bug, feature

#20 Fix: #17 unique "key" prop 에러 수정
  app/src/components/CardList.jsx
  app/src/components/Category.jsx
  app/src/components/Header.jsx
  app/src/components/MainCategories.jsx
  app/src/components/Slider.jsx
Labels: bug
